<a href="https://colab.research.google.com/github/COAP230023/atividade-praticas-em-numpy-AgeuGuedes/blob/main/Pratica01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 1. Vetor de zeros  _(fácil)_

Crie um array 1D com 10 zeros usando NumPy e mostre o dtype e o shape.


In [ ]:
import numpy as np

array_zeros = np.zeros(10)

print(array_zeros)
print("Dtype:", array_zeros.dtype)
print("Shape:", array_zeros.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Dtype: float64
Shape: (10,)


### 2. Vetor de uns  _(fácil)_

Crie um array 1D com 10 uns e transforme-o em float64.

In [ ]:
import numpy as np

array_uns_float = np.ones(10, dtype=np.float64)

print(array_uns_float)
print(array_uns_float.dtype)
print(array_uns_float.shape)

### 3. Sequência 0–9  _(fácil)_

Crie um array com os inteiros de 0 a 9 (inclusive).

In [ ]:
import numpy as np

array_sequencia = np.arange(10)

print(array_sequencia)

[0 1 2 3 4 5 6 7 8 9]


### 4. Matriz 3×3 com 0…8  _(fácil)_

Crie um array 3×3 com os valores 0…8 (reshape).

In [ ]:
import numpy as np

matriz_3x3 = np.arange(9).reshape(3, 3)

print(matriz_3x3)

### 5. Índices não zero  _(fácil)_

Dado o vetor `v = np.array([1,2,0,0,4,0])`, encontre os índices dos elementos não nulos.

In [ ]:
import numpy as np

v = np.array([1, 2, 0, 0, 4, 0])
indices_nao_zero = np.nonzero(v)

print(indices_nao_zero)

### 6. Linspace  _(fácil)_

Crie um vetor de 12 pontos igualmente espaçados no intervalo [0, 1].

In [ ]:
import numpy as np

vetor_linspace = np.linspace(0, 1, 12)

print(vetor_linspace)

### 7. Identidade 5×5  _(fácil)_

Crie uma matriz identidade de ordem 5.

In [ ]:
import numpy as np

matriz_identidade_5x5 = np.eye(5)

print(matriz_identidade_5x5)

### 8. Aleatórios 3×3×3  _(fácil)_

Gere um array 3×3×3 com valores aleatórios uniformes em [0,1). Use `np.random.default_rng(42)`.

In [ ]:
import numpy as np

rng = np.random.default_rng(42)
array_aleatorio_3x3x3 = rng.random((3, 3, 3))

print(array_aleatorio_3x3x3)

### 9. Min/Max  _(fácil)_

Crie uma matriz 10×10 de aleatórios uniformes e mostre o valor mínimo e máximo.

In [ ]:
import numpy as np

rng = np.random.default_rng()
matriz_10x10 = rng.random((10, 10))

valor_minimo = matriz_10x10.min()
valor_maximo = matriz_10x10.max()

print("Matriz (amostra):\n", matriz_10x10[:2, :2])
print("Valor Mínimo:", valor_minimo)
print("Valor Máximo:", valor_maximo)

### 10. Padronização 1D  _(fácil)_

Dado `x = [1,2,3,4,5]`, crie um array float e normalize para média 0 e desvio 1.

In [ ]:
import numpy as np

x = np.array([1, 2, 3, 4, 5], dtype=np.float64)

media = x.mean()
desvio_padrao = x.std()

x_normalizado = (x - media) / desvio_padrao

print(x_normalizado)
print("Média (aprox.):", x_normalizado.mean())
print("Desvio Padrão (aprox.):", x_normalizado.std())

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
Média (aprox.): 0.0
Desvio Padrão (aprox.): 0.9999999999999999


### 11. Conversão de tipos  _(fácil)_

Converta `np.array([1,2,3])` (int32) para float32 e depois para int64.

In [ ]:
import numpy as np

array_original = np.array([1, 2, 3], dtype=np.int32)

array_float32 = array_original.astype(np.float32)

array_int64 = array_float32.astype(np.int64)

print("Original (int32):", array_original, array_original.dtype)
print("Para float32:", array_float32, array_float32.dtype)
print("Para int64:", array_int64, array_int64.dtype)

Original (int32): [1 2 3] int32
Para float32: [1. 2. 3.] float32
Para int64: [1 2 3] int64


### 12. Clipping  _(fácil)_

Dado `a = [2, 5, 7, 1, 9]`, limite os valores ao intervalo [0,5] (valores acima de 5 tornam-se 5).

In [ ]:
import numpy as np

a = np.array([2, 5, 7, 1, 9])
a_clipped = np.clip(a, 0, 5)

print(a_clipped)

### 13. Inversão  _(fácil)_

Crie um vetor de 0 a 9 e inverta a ordem (sem usar `[::-1]`).


In [ ]:
import numpy as np

vetor_original = np.arange(10)
vetor_invertido = np.flip(vetor_original)

print(vetor_invertido)

[9 8 7 6 5 4 3 2 1 0]


### 14. Empilhamento  _(fácil)_

Dado `a = [1,2,3]` e `b = [4,5,6]`, empilhe horizontal e verticalmente.

In [11]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

vertical_stack = np.vstack((a, b))

horizontal_stack = np.hstack((a, b))

print("Array a:", a)
print("Array b:", b)
print("\nEmpilhamento Vertical:\n", vertical_stack)
print("Shape:", vertical_stack.shape)
print("\nEmpilhamento Horizontal:\n", horizontal_stack)
print("Shape:", horizontal_stack.shape)

Array a: [1 2 3]
Array b: [4 5 6]

Empilhamento Vertical:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)

Empilhamento Horizontal:
 [1 2 3 4 5 6]
Shape: (6,)


### 15. Diagonal  _(fácil)_

Crie uma matriz 4×4 com a diagonal principal igual a 5 e as demais entradas zero.

In [ ]:
import numpy as np

matriz_diag = 5 * np.eye(4)

print(matriz_diag)

### 16. Somas por eixo  _(fácil)_

Para a matriz `A = np.arange(12).reshape(3,4)`, calcule a soma por linhas e por colunas.

In [ ]:
import numpy as np

A = np.arange(12).reshape(3, 4)

soma_linhas = A.sum(axis=1)

soma_colunas = A.sum(axis=0)

print("Matriz A:\n", A)
print("\nSoma por linhas (axis=1):", soma_linhas)
print("Soma por colunas (axis=0):", soma_colunas)

### 17. Frequências inteiras  _(fácil)_

Gere 100 inteiros aleatórios em [0,9] e conte as frequências de cada valor (0 a 9).

In [ ]:
import numpy as np

inteiros = rng.integers(low=0, high=10, size=100)

frequencias = np.bincount(inteiros, minlength=10)

print("Primeiros 20 inteiros gerados:", inteiros[:20])
print("\nFrequências (para 0, 1, ..., 9):")
print(frequencias)

### 18. Slicing com passo  _(fácil)_

Dado `v = np.arange(20)`, selecione cada 3º elemento começando do índice 1.

In [ ]:
import numpy as np

v = np.arange(20)

resultado = v[1::3]

print("Vetor original:", v)
print("Cada 3º elemento a partir do índice 1:", resultado)

### 19. Máscara booleana  _(fácil)_

Crie uma máscara para números pares de `0…19` e use-a para filtrar o vetor.

In [ ]:
import numpy as np

v = np.arange(20)

mascara_par = (v % 2 == 0)

vetor_pares = v[mascara_par]

print("Vetor original:", v)
print("Máscara (Par?):", mascara_par)
print("Vetor filtrado (só pares):", vetor_pares)

### 20. Lista de listas → array  _(fácil)_

Converta `[[1,2,3],[4,5,6]]` em `ndarray`, verifique `shape` e `dtype`.

In [ ]:
import numpy as np

lista_de_listas = [[1, 2, 3], [4, 5, 6]]

meu_array = np.array(lista_de_listas)

print("Array NumPy:\n", meu_array)
print("Shape:", meu_array.shape)
print("Dtype:", meu_array.dtype)

### 21. Datas básicas  _(fácil)_

Crie um array de datas diárias de 2025-01-01 a 2025-01-07 (inclusive).


In [ ]:
import numpy as np

datas = np.arange('2025-01-01', '2025-01-08', dtype='datetime64[D]')

print(datas)

### 22. Centralizar colunas  _(fácil)_

Dada `A = np.array([[1.,2.,3.],[4.,5.,6.]])`, subtraia a média de cada coluna.

In [ ]:
import numpy as np

A = np.array([[1., 2., 3.], [4., 5., 6.]])

media_colunas = A.mean(axis=0)

A_centralizado = A - media_colunas

print("Matriz Original:\n", A)
print("\nMédia das colunas:", media_colunas)
print("\nMatriz Centralizada:\n", A_centralizado)
print("\nNova média das colunas (deve ser ~0):\n", A_centralizado.mean(axis=0))

### 23. Produto elemento-a-elemento vs. escalar  _(fácil)_

Dadas `a=[1,2,3]` e `b=[4,5,6]`, calcule produto elemento a elemento e o produto escalar.

In [12]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

produto_elemento = a * b

produto_escalar = np.dot(a, b)

print("Array a:", a)
print("Array b:", b)
print("\nProduto Elemento-a-Elemento (a * b):", produto_elemento)
print("Produto Escalar (np.dot(a, b)):", produto_escalar)

Array a: [1 2 3]
Array b: [4 5 6]

Produto Elemento-a-Elemento (a * b): [ 4 10 18]
Produto Escalar (np.dot(a, b)): 32


### 24. Troca de colunas  _(fácil)_

Troque as colunas 0 e 2 de `A = np.arange(12).reshape(3,4)` sem copiar (sempre que possível).

In [10]:
import numpy as np

A = np.arange(12).reshape(3, 4)
print("Matriz Original:\n", A)

A[:, [0, 2]] = A[:, [2, 0]]

print("\nMatriz com colunas 0 e 2 trocadas:\n", A)

Matriz Original:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Matriz com colunas 0 e 2 trocadas:
 [[ 2  1  0  3]
 [ 6  5  4  7]
 [10  9  8 11]]


### 25. Flatten vs. ravel  _(médio)_

Mostre a diferença entre `flatten()` (cópia) e `ravel()` (view quando possível). Modifique o resultado de `ravel()` e observe o original.

In [9]:
import numpy as np

A = np.arange(6).reshape(2, 3)
print("Matriz Original A:\n", A)

print("\n--- Testando ravel() ---")
r = A.ravel()
r[0] = 99
print("A foi modificado? (Sim):\n", A)

A[0, 0] = 0
print("\nMatriz A resetada:\n", A)

print("\n--- Testando flatten() ---")
f = A.flatten()
f[0] = 77
print("A foi modificado? (Não):\n", A)
print("Array 'f' (a cópia):\n", f)

Matriz Original A:
 [[0 1 2]
 [3 4 5]]

--- Testando ravel() ---
A foi modificado? (Sim):
 [[99  1  2]
 [ 3  4  5]]

Matriz A resetada:
 [[0 1 2]
 [3 4 5]]

--- Testando flatten() ---
A foi modificado? (Não):
 [[0 1 2]
 [3 4 5]]
Array 'f' (a cópia):
 [77  1  2  3  4  5]


### 26. Tabuleiro 8×8  _(médio)_

Crie uma matriz 8×8 com padrão de tabuleiro (0 e 1 alternados).

In [8]:
import numpy as np

tabuleiro = np.zeros((8, 8), dtype=int)

tabuleiro[1::2, ::2] = 1

tabuleiro[::2, 1::2] = 1

print(tabuleiro)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 27. np.where condicional  _(médio)_

Dado `x = np.arange(-5,6)`, substitua negativos por 0 e mantenha não-negativos.

In [5]:
import numpy as np

x = np.arange(-5, 6)

resultado = np.where(x < 0, 0, x)

print("Vetor Original:", x)
print("Vetor modificado:", resultado)

Vetor Original: [-5 -4 -3 -2 -1  0  1  2  3  4  5]
Vetor modificado: [0 0 0 0 0 0 1 2 3 4 5]


### 28. Precisão de média  _(médio)_

Gere 1_000_000 floats uniformes em [0,1) e compute a média. Compare com o valor teórico 0.5 (erro absoluto).

In [ ]:
import numpy as np

rng = np.random.default_rng(seed=42)

dados = rng.random(1_000_000)

media_calculada = dados.mean()
valor_teorico = 0.5

erro_abs = np.abs(media_calculada - valor_teorico)

print(f"Total de números: {len(dados)}")
print(f"Média calculada: {media_calculada}")
print(f"Valor teórico:   {valor_teorico}")
print(f"Erro absoluto:   {erro_abs}")

### 29. Produto cartesiano (broadcasting)  _(médio)_

Dado `a=[1,2,3]` e `b=[10,20,30,40]`, gere todas as somas possíveis `a_i + b_j` via broadcasting (matriz 3×4).

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([10, 20, 30, 40])

a_coluna = a[:, np.newaxis]

somas_broadcast = a_coluna + b

print("a (coluna 3x1):\n", a_coluna)
print("\nb (linha 1x4):", b)
print("\nSomas (broadcasting 3x4):\n", somas_broadcast)

### 30. Convolução 1D simples  _(médio)_

Implemente uma convolução 1D 'valid' de um sinal `s` por um kernel `k` usando `np.flip` e `np.lib.stride_tricks.sliding_window_view` (sem `np.convolve`).

In [ ]:
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view

sinal = np.array([1, 2, 3, 4, 5, 6])
kernel = np.array([1, 0, -1])

kernel_invertido = np.flip(kernel)

tamanho_kernel = len(kernel)
janelas = sliding_window_view(sinal, window_shape=tamanho_kernel)

conv_valid = janelas @ kernel_invertido

print("Sinal:", sinal)
print("Kernel:", kernel)
print("Janelas (views):\n", janelas)
print("Kernel invertido:", kernel_invertido)
print("\nResultado da Convolução 'valid':", conv_valid)

### 31. Normalização min–max por coluna  _(médio)_

Dada `A = rng.normal(size=(5,4))`, normalize cada coluna para o intervalo [0,1], tratando colunas constantes.

In [ ]:
import numpy as np

rng = np.random.default_rng(seed=42)

A = rng.normal(size=(5, 4))
print("Matriz Original A:\n", A)

col_min = A.min(axis=0)
col_max = A.max(axis=0)

col_range = col_max - col_min

col_range[col_range == 0] = 1

A_norm = (A - col_min) / col_range

print("\nMínimos por coluna:", col_min)
print("Máximos por coluna:", col_max)
print("\nMatriz Normalizada [0, 1]:\n", A_norm)

print("\nNovo Mínimo (deve ser 0):", A_norm.min(axis=0))
print("Novo Máximo (deve ser 1):", A_norm.max(axis=0))

### 32. Ordenar por coluna  _(médio)_

Ordene as linhas de `A = np.array([[3,9],[1,4],[2,5]])` pelo valor crescente da 2ª coluna.


In [ ]:
import numpy as np

A = np.array([[3, 9], [1, 4], [2, 5]])
print("Matriz Original A:\n", A)

coluna_ordenacao = A[:, 1]

indices_ordenados = np.argsort(coluna_ordenacao)

A_ordenado = A[indices_ordenados]

print("\nÍndices ordenados (da 2ª col):", indices_ordenados)
print("\nMatriz ordenada pela 2ª coluna:\n", A_ordenado)

### 33. Únicos + contagens + primeira ocorrência  _(médio)_

Para `x = [3,1,2,3,2,3,1]`, obtenha valores únicos, contagens e índice da primeira ocorrência de cada valor.

In [ ]:
import numpy as np

x = np.array([3, 1, 2, 3, 2, 3, 1])

unicos, idx_primeira, contagens = np.unique(x,
                                           return_index=True,
                                           return_counts=True)

print("Vetor original:", x)
print("\nValores únicos:", unicos)
print("Índice da primeira ocorrência:", idx_primeira)
print("Contagem de cada valor:", contagens)

### 34. Matriz de distâncias 2D  _(médio)_

Dada `P` com N pontos 2D, compute a matriz NxN de distâncias euclidianas sem loops explícitos.

In [ ]:
import numpy as np

rng = np.random.default_rng(seed=42)

P = rng.random(size=(5, 2))
print("Pontos P (Shape 5x2):\n", P)

diff = P[:, np.newaxis, :] - P[np.newaxis, :, :]

dist_sq = np.sum(diff**2, axis=-1)

matriz_dist = np.sqrt(dist_sq)

print("\nMatriz de Distâncias Euclidianas (5x5):\n", matriz_dist)

### 35. Covariância e correlação  _(médio)_

Simule uma matriz 1000×3 de N(0,1) e compute `cov` (colunas como variáveis) e `corrcoef`.

In [ ]:
import numpy as np

rng = np.random.default_rng(seed=42)

X = rng.normal(size=(1000, 3))

matriz_cov = np.cov(X, rowvar=False)

matriz_corr = np.corrcoef(X, rowvar=False)

print(f"Shape de X (observações, variáveis): {X.shape}")
print("\nMatriz de Covariância (3x3):\n", matriz_cov)
print("\nMatriz de Correlação (3x3):\n", matriz_corr)

### 36. One-hot encoding  _(médio)_

Converta os rótulos `y = [2,0,1,2]` em codificação one-hot usando apenas operações NumPy.

In [ ]:
import numpy as np

y = np.array([2, 0, 1, 2])
print("Rótulos (y):", y)

num_classes = np.max(y) + 1
num_amostras = len(y)

one_hot = np.zeros((num_amostras, num_classes), dtype=int)

one_hot[np.arange(num_amostras), y] = 1

print(f"\nShape: ({num_amostras}, {num_classes})")
print("Codificação One-Hot:\n", one_hot)

### 37. k-means 2D (NumPy puro)  _(difícil)_

Implemente k-means com K=3 em pontos 2D: inicialize centróides aleatórios, faça 10 iterações de (1) atribuir pontos ao centróide mais próximo e (2) recomputar centróides.


In [ ]:
import numpy as np

rng = np.random.default_rng(seed=42)

K = 3
N_pontos = 100
pontos = rng.random(size=(N_pontos, 2))

idx_inicio = rng.choice(N_pontos, K, replace=False)
centroides = pontos[idx_inicio]

print("Centróides Iniciais:\n", centroides)

for i in range(10):
    dist = pontos[:, np.newaxis, :] - centroides[np.newaxis, :, :]
    dist_sq = np.sum(dist**2, axis=2)

    labels = np.argmin(dist_sq, axis=1)

    novos_centroides = np.zeros((K, 2))
    for k in range(K):
        pontos_do_cluster_k = pontos[labels == k]
        if len(pontos_do_cluster_k) > 0:
            novos_centroides[k] = pontos_do_cluster_k.mean(axis=0)

    centroides = novos_centroides

print(f"\nCentróides Finais (após 10 iterações):\n", centroides)

### 38. PCA básica (autovetores)  _(difícil)_

Implemente PCA 2D→1D: centralize `X` (N×2), calcule covariância, autovetores, projete em 1D e reconstrua aproximado.


In [ ]:
import numpy as np

rng = np.random.default_rng(seed=42)

X = rng.normal(size=(100, 2))
X[:, 1] = X[:, 0] * 0.8 + rng.normal(size=100) * 0.3
print("Shape dados X:", X.shape)

X_mean = X.mean(axis=0)
X_centered = X - X_mean

cov_matrix = np.cov(X_centered, rowvar=False)
print("\nMatriz Covariância (2x2):\n", cov_matrix)

autovalores, autovetores = np.linalg.eigh(cov_matrix)
print("\nAutovalores:", autovalores)
print("Autovetores:\n", autovetores)

indices_sort = np.argsort(autovalores)[::-1]
autovetores_sorted = autovetores[:, indices_sort]

W = autovetores_sorted[:, :1]
print("\n1º Componente Principal (W):\n", W)

Z = X_centered @ W
print("\nDados Projetados (Z) (100x1) (primeiros 5):", Z[:5].ravel())

X_reconstruido_centered = Z @ W.T

X_reconstruido = X_reconstruido_centered + X_mean
print("\nShape Reconstruído:", X_reconstruido.shape)

### 39. Convolução 2D (im2col)  _(difícil)_

Implemente convolução 2D 'valid' de uma imagem `I` por um kernel `K` usando `sliding_window_view` para gerar blocos e multiplicação matricial.

In [ ]:
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view

I = np.arange(25).reshape(5, 5).astype(float)
K = np.array([[1, 0, -1],
              [1, 0, -1],
              [1, 0, -1]], dtype=float)

kH, kW = K.shape
iH, iW = I.shape

views = sliding_window_view(I, window_shape=(kH, kW))
print(f"Shape Imagem: {I.shape}")
print(f"Shape Kernel: {K.shape}")
print(f"Shape das Janelas (Views): {views.shape}")

K_flat = K.ravel()
print(f"Shape Kernel achatado: {K_flat.shape}")

views_flat = views.reshape(-1, kH * kW)
print(f"Shape Janelas achatadas: {views_flat.shape}")

conv_flat = views_flat @ K_flat

output_shape = (iH - kH + 1, iW - kW + 1)
conv_2d = conv_flat.reshape(output_shape)

print("\nConvolução 2D 'valid' (resultado):\n", conv_2d)

### 40. Sistemas lineares e resíduo  _(difícil)_

Gere uma matriz A (100×100) bem-condicionada, um vetor b e resolva `Ax=b` com `np.linalg.solve`. Compute o resíduo relativo `||Ax−b||/||b||` e `cond(A)`.

In [ ]:
import numpy as np

rng = np.random.default_rng(seed=42)

N = 100

A = rng.random(size=(N, N)) + np.eye(N) * N
b = rng.random(size=N)

x = np.linalg.solve(A, b)

residuo = (A @ x) - b

norma_residuo = np.linalg.norm(residuo)
norma_b = np.linalg.norm(b)
residuo_relativo = norma_residuo / norma_b

cond_A = np.linalg.cond(A)

print(f"Sistema N={N}")
print(f"Número de Condição cond(A): {cond_A}")
print(f"Norma do Resíduo ||Ax - b||: {norma_residuo}")
print(f"Norma de b ||b||: {norma_b}")
print(f"Resíduo Relativo ||Ax - b|| / ||b||: {residuo_relativo}")

### 41. Regressão linear (OLS) com NumPy  _(difícil)_

Dado `X` (N×d) e `y`, calcule os coeficientes OLS usando `np.linalg.lstsq` e avalie RMSE no treino.

In [6]:
import numpy as np

rng = np.random.default_rng(seed=42)

N, d = 100, 3
X = rng.random(size=(N, d))

beta_verdadeiro = np.array([5.0, -2.0, 1.5])
intercepto_verdadeiro = 3.0
ruido = rng.normal(scale=0.1, size=N)

y = intercepto_verdadeiro + (X @ beta_verdadeiro) + ruido

X_b = np.hstack([np.ones((N, 1)), X])
print(f"Shape X original: {X.shape}, Shape y: {y.shape}")
print(f"Shape X com intercepto (X_b): {X_b.shape}")

coefs, _, _, _ = np.linalg.lstsq(X_b, y, rcond=None)

intercepto_calc = coefs[0]
betas_calc = coefs[1:]

print("\n--- Resultados OLS ---")
print(f"Intercepto Verdadeiro (B0): {intercepto_verdadeiro:.4f}")
print(f"Intercepto Calculado: {intercepto_calc:.4f}")
print(f"\nBetas Verdadeiros (B1, B2, B3): {beta_verdadeiro}")
print(f"Betas Calculados: {betas_calc}")

y_pred = X_b @ coefs
mse = np.mean((y - y_pred)**2)
rmse = np.sqrt(mse)

print(f"\nRMSE (no treino): {rmse:.5f}")

Shape X original: (100, 3), Shape y: (100,)
Shape X com intercepto (X_b): (100, 4)

--- Resultados OLS ---
Intercepto Verdadeiro (B0): 3.0000
Intercepto Calculado: 3.0109

Betas Verdadeiros (B1, B2, B3): [ 5.  -2.   1.5]
Betas Calculados: [ 5.01368109 -1.98126003  1.46262967]

RMSE (no treino): 0.10147


### 42. Rolling window 2D com strides  _(difícil)_

Usando `sliding_window_view`, compute a média local 3×3 de uma imagem 2D sem laços explícitos.

In [7]:
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view

I = np.arange(36).reshape(6, 6)
print("Imagem Original (6x6):\n", I)

window_shape = (3, 3)

views = sliding_window_view(I, window_shape=window_shape)
print("\nShape das Views (Janelas):", views.shape)

media_local = views.mean(axis=(2, 3))

print("\nMatriz de Média Local 3x3 (4x4):\n", media_local)

Imagem Original (6x6):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

Shape das Views (Janelas): (4, 4, 3, 3)

Matriz de Média Local 3x3 (4x4):
 [[ 7.  8.  9. 10.]
 [13. 14. 15. 16.]
 [19. 20. 21. 22.]
 [25. 26. 27. 28.]]
